Added time slots for book and update deliveries
iferunsewe/foremore pull request #1
Opened 2023-05-05 14:15 UTC by gotoinc

2023-05-07 22:33 UTC, iferunsewe requested changes

2023-05-07 22:33 UTC, iferunsewe commented on app/controllers/deliveries_controller.rb
> +      a = params.require(:delivery).permit(
Why are you setting this to a variable?

2023-05-07 22:33 UTC, iferunsewe commented on app/controllers/deliveries_controller.rb
> +      a = params.require(:delivery).permit(
Also please use descriptive variable names

2023-05-07 22:33 UTC, iferunsewe commented on app/helpers/deliveries_helper.rb
> +    # formatted_slots = time_slots.each_with_object([]).with_index do |(time, arr), index|
Why is this code in here?

2023-05-07 22:33 UTC, iferunsewe commented on app/javascript/controllers/application.js
> +
Please move this code to a stimulus controller and avoid adding code to this file

2023-05-07 22:33 UTC, iferunsewe commented on app/javascript/controllers/delivery_price_controller.js
> +        // this.deliveryDayLabelTarget.innerText = "Today"
Please don't leave in code that isn't being used

2023-05-07 22:33 UTC, iferunsewe commented on app/javascript/controllers/delivery_price_controller.js
> +    // const lastSelectedTimeSlot = selectedTimeSlots[selectedTimeSlots.length -1]
Please don't leave in code that isn't being used

2023-05-07 22:33 UTC, iferunsewe commented on app/javascript/utils/delivery_type.js
> +}
This shouldn't be necessary. I rather set up these time slots on the rails side of things using rails helps and manipulate the element attributes using stimulus js

2023-05-07 22:33 UTC, iferunsewe commented on app/services/team_services/time_processor.rb
> +      time_slots = @team.week_days_options.each_with_object({}) do |(k, v), h|
please use descriptive variable names

2023-05-07 22:36 UTC, iferunsewe commented on config/environments/development.rb
> +  config.assets.compile = true
Why was this needed?

2023-05-07 22:37 UTC, iferunsewe commented on app/views/deliveries/form/_guest_form.html.erb
> +        <%= render "deliveries/form/delivery_type", { form: form, delivery: delivery } %>
Why did was the order of the components changed?

2023-05-07 22:47 UTC, iferunsewe commented
<img width="306" alt="Screenshot 2023-05-07 at 23 40 39" src="https://user-images.githubusercontent.com/8715417/236706161-5aad8168-ef59-45c7-b48d-13c9cf361069.png">

When the time slots are shown on mobile, the width of the timeslots is not the full width of the container. Please the red line in the screenshot to understand the problem

2023-05-07 22:50 UTC, iferunsewe commented
<img width="314" alt="Screenshot 2023-05-07 at 23 42 12" src="https://user-images.githubusercontent.com/8715417/23
<img width="307" alt="Screenshot 2023-05-07 at 23 43 25" src="https://user-images.githubusercontent.com/8715417/236706256-20efbc1e-0690-4e3c-923b-3bd11f804315.png">
6706234-ef4e2a07-aefb-4ccf-b0fd-7dd414982f33.png">

Both displays of the timeslot should be the same. You can use the already built logic on the server from the first screenshot in the second screen

2023-05-07 22:51 UTC, iferunsewe commented
<img width="307" alt="Screenshot 2023-05-07 at 23 43 25" src="https://user-images.githubusercontent.com/8715417/236706323-b68cbbc3-5b2e-4ff9-a278-2ab49182b3e5.png">
The logic for showing which timeslots are selected is not working. As you can see in the screenshot:
1. I selected 12:00
2. Then unselected 12.00
3. However it was still highlighted whereas it should be unhighlighted

2023-05-09 11:06 UTC, gotoinc commented on app/views/deliveries/form/_guest_form.html.erb
> +        <%= render "deliveries/form/delivery_type", { form: form, delivery: delivery } %>
Each team has its own settings for time slots, so in order for the time slot mechanism to work, it is necessary to define team first (to select address).
As soon as we select the team, we immediately load the necessary time slots.

2023-05-09 13:44 UTC, gotoinc commented on app/controllers/deliveries_controller.rb
> +      a = params.require(:delivery).permit(
Because I should merge blank Json for `scheduled_time_slots` for delivery, it needs to switch the type of delivery from scheduled to fast one.

2023-05-11 16:38 UTC, iferunsewe commented on app/views/dashboards/_next_deliveries.html.erb
> +                <%= button_to delivery_path(delivery), data: { turbo: false }, method: :patch, class: 'btn btn-secondary mb-2 col-12', params: { delivery: {status: "ready", scheduled_time_slots: deli
This can't be the way to fix this problem as every time I create an action button for deliveries, we must remember to add the scheduled_time_slots

2023-05-11 21:32 UTC, iferunsewe approved these changes
Thanks for your work @gotoinc

2023-05-11 21:32 UTC, merged