Customer show page
iferunsewe/foremore pull request #12
Opened 2023-06-20 16:32 UTC by gotoinc

2023-06-21 06:53 UTC, iferunsewe commented on app/controllers/customers_controller.rb
> +  def new_address
This should be in it's own "AddressController"?

2023-06-21 06:59 UTC, iferunsewe requested changes
The address and customer server code should be seperated

2023-06-21 06:59 UTC, iferunsewe commented on app/helpers/application_helper.rb
> +  def prepend_flash
Why is this needed?

2023-06-21 09:23 UTC, gotoinc commented on app/helpers/application_helper.rb
> +  def prepend_flash
This helper allows me to show flash with turbo_stream response. I see that I wrote this helper only for div#flash2. I can add tag_id variable to do this method more reusable. Also, suggest renaming flash2 to addresses_flash.

2023-06-21 10:30 UTC, iferunsewe commented on app/helpers/application_helper.rb
> +  def prepend_flash
Lets rename it to `prepend_flash_to_turbo` as it won't just be used for `addresses`

2023-06-21 17:28 UTC, iferunsewe commented on app/controllers/customers/addresses_controller.rb
> +    def new_address
Can these just be the normal action names like e.g. "new", "create", "edit" , "update", "destroy"

2023-06-22 14:02 UTC, gotoinc commented on app/helpers/application_helper.rb
> +  def prepend_flash
okay

2023-06-23 08:16 UTC, iferunsewe approved these changes

2023-06-23 11:39 UTC, merged